name: workflow

on:
    - push

jobs:
    setup-skaffold:
        name: Setup Skaffold

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3.6.0

            - uses: ./

            - run: skaffold help
